//All Products
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"

//Solo Products
export const GET_SOLO_REQUEST = "GET_SOLO_REQUEST"
export const GET_SOLO_SUCCESS = "GET_SOLO_SUCCESS"
export const GET_SOLO_FAILURE = "GET_SOLO_FAILURE"

 
 