export const GET_JOBS_REQUEST = "GET_JOBS_REQUEST";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_FAILURE = "GET_JOBS_FAILURE";
export const REMOTE_REQUEST = "REMOTE_REQUEST";
export const REMOTE_SUCCESS = "REMOTE_SUCCESS";
export const REMOTE_FAILURE = "REMOTE_FAILURE";